language: node_js

node_js: 8

install:
  - yarn install

script:
  - yarn lint
  - yarn test:with-coverage | coveralls
  # --stream causes more output so CI doesn't timeout
  - yarn build --stream

cache: yarn
