apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  template:
    metadata:
      labels:
        app: website
        tier: frontend
    spec:
      containers:
      - name: drawbydays-website
        image: sketchingdev/drawbydays-website:latest
        ports:
        - containerPort: 80
        env:
        - name: SERVER_PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    tier: frontend
