version: 2.1

commands:
  yarn-install-with-cache:
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install YARN dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
#  yarn-build-then-test:
#  yarn-build:
#    parameters:
#      package_name:
#        type: string
#    steps:
#      - run:
#          name: Build
#          command: yarn build
#      - run:
#          name: Test
#          command: yarn test --scope << parameters.package_name >>
#      - store_test_results:
#          path: ./packages/<< parameters.package_name >>/reports/

executors:
  node-build-environment:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
#  serverless-deploy-environment:
#    docker:
#      - image: amaysim/serverless:1.36.3
#    working_directory: ~/repo

jobs:
  build-all:
    executor: node-build-environment
    steps:
      - checkout
      - yarn-install-with-cache
      - run:
          name: Build Services
          command: yarn build

  test-all:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8-browsers
      - image: localstack/localstack
        environment:
          SERVICES: dynamodb:4569,s3:5000,sqs
    steps:
      - setup_remote_docker
      - checkout
      - yarn-install-with-cache
      - run:
          name: Test Services
          command: yarn test

  component-test-all:
    executor: node-build-environment
    steps:
      - setup_remote_docker
      - checkout
      - yarn-install-with-cache
      - run:
          name: Component Test Services
          command: yarn test:component

workflows:
  version: 2

  commit_jobs:
    jobs:
      - build-all
      - test-all
      - component-test-all:
          requires:
            - build-all
            - test-all
