version: 2.1

commands:
  # TODO Build custom image that chmod's and creates an alias
  prepare-scripts:
    steps:
      - run: chmod +x .circleci/scripts/redact.sh

  yarn-install-with-cache:
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install YARN dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

executors:
  node-build-environment:
    docker:
      - image: circleci/node:8-browsers
    environment:
      # Forces yarn to preserve colour output (https://github.com/yarnpkg/yarn/issues/5733)
      FORCE_COLOR: true
    working_directory: ~/repo

jobs:
  build-all:
    executor: node-build-environment
    steps:
      - checkout
      - prepare-scripts
      - yarn-install-with-cache
      - run:
          name: Build Services
          command: yarn build | .circleci/scripts/redact.sh

  test-all:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8-browsers
      - image: localstack/localstack
        environment:
          SERVICES: dynamodb:4569,s3:5000,sqs
    steps:
      - setup_remote_docker
      - checkout
      - prepare-scripts
      - yarn-install-with-cache
      - run:
          name: Test Services
          command: yarn test | .circleci/scripts/redact.sh

  component-test-all:
    executor: node-build-environment
    steps:
      - checkout
      - prepare-scripts
      - yarn-install-with-cache
      - run:
          name: Component Test Services
          command: yarn test:component | .circleci/scripts/redact.sh

  e2e-test:
    executor: node-build-environment
    steps:
      - checkout
      - prepare-scripts
      - yarn-install-with-cache
      - run:
          name: Deploy CI environment
          command: yarn deploy:ci | .circleci/scripts/redact.sh
      - run:
          name: E2E Test Services
          command: yarn test:e2e | .circleci/scripts/redact.sh
      - store_artifacts:
          path: packages/e2e/cypress/screenshots
      - store_artifacts:
          path: packages/e2e/cypress/videos

  e2e-test-cleanup:
    executor: node-build-environment
    steps:
      - checkout
      - prepare-scripts
      - yarn-install-with-cache
      - run:
          name: Remove CI environment
          command: yarn remove:ci | .circleci/scripts/redact.sh

  deploy-prod:
    executor: node-build-environment
    steps:
      - checkout
      - prepare-scripts
      - yarn-install-with-cache
      - run:
          name: Deploy production environment
          command: yarn deploy:prod | .circleci/scripts/redact.sh

workflows:
  version: 2

  commit_jobs:
    jobs:
      - build-all:
          filters:
            branches:
              ignore:
                - master
      - test-all:
          filters:
            branches:
              ignore:
                - master
      - component-test-all:
          requires:
            - build-all
            - test-all
          filters:
            branches:
              ignore:
                - master
      - e2e-test:
          requires:
            - component-test-all

  master:
    jobs:
      - build-all:
          filters:
            branches:
              only:
                master
      - deploy-prod:
          requires:
            - build-all

  nightly-ci-teardown:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - rewrite-with-serverless
    jobs:
      - e2e-test-cleanup
