version: 2.1

commands:
  yarn-install-with-cache:
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install YARN dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  yarn-build-then-test:
    parameters:
      package_name:
        type: string
    steps:
      - run:
          name: Build
          command: yarn build --scope << parameters.package_name >> --include-filtered-dependencies
      - run:
          name: Test
          command: yarn test --scope << parameters.package_name >>
      - store_test_results:
          path: ./packages/<< parameters.package_name >>/reports/

executors:
  node-build-environment:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
  serverless-deploy-environment:
    docker:
      - image: amaysim/serverless:1.36.3
    working_directory: ~/repo

jobs:

  ## Website

  test_website:
    executor: node-build-environment
    steps:
      - checkout
      - yarn-install-with-cache
      - yarn-build-then-test:
          package_name: website

workflows:
  version: 2

  commit_jobs:
    jobs:

      ## Website

      - test_website
#      - build_website
#      - deploy_website:
#          requires:
#            - build_website
