service:
  name: website

plugins:
  - serverless-finch
  - serverless-stage-manager

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}

custom:
  stages:
    - dev
    - ci
    - prod
  siteName:
    dev: dev.drawbydays.com
    ci: ci.drawbydays.com
    prod: drawbydays.com
  client:
    bucketName: ${self:custom.siteName.${self:provider.stage}}
    distributionFolder: build/
  domain:
    name: ${self:custom.siteName.${self:provider.stage}}
    hostedZoneName: drawbydays.com.
    usEastOneZoneId: Z3AQBSTGFYJSTF

resources:
  Resources:
    S3WebsiteDnsEntry:
      Type: AWS::Route53::RecordSet
      Properties:
        Name: ${self:custom.domain.name}
        HostedZoneName: ${self:custom.domain.hostedZoneName}
        Type: A
        AliasTarget:
          DNSName: s3-website-us-east-1.amazonaws.com
          HostedZoneId: ${self:custom.domain.usEastOneZoneId}
