spring:
  messages:
    basename: i18n/messages

  datasource:
    url: jdbc:h2:mem:website;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver

app:
  images:
    - ./images/fountain.png
    - ./images/manor.png